Repository open-source-uc/web, pull requests merged in 2021-05, with the labels that each got.

#10 Cleaning
  css/opensource_uc.css
  img/map.png
  index.html
Labels: enhancement

#12 Proyectos
  index.html
  mock/article.json
Labels: bug, enhancement, help wanted

#11 Contacto
  css/opensource_uc.css
  index.html
Labels: enhancement

#22 Team update
  README.md
  assets/.keep
  assets/data/.keep
  assets/data/members-manifest.json
  css/opensource_uc.css
  index.html
  js/load-team.js
  mock/article.json
Labels: enhancement, good first issue

#27 devuelvo y actualizo json
  assets/data/projects.json
  js/stisla.js
Labels: bug

#29 fix: add template keyword
  .github/PULL_REQUEST_TEMPLATE/feature_template.md
Labels: bug

#34 Propuesta proyectos emoji hover gif
  assets/data/projects.json
  css/opensource_uc.css
  index.html
Labels: enhancement

#31 Eug dev
  index.html
Labels: enhancement

#42 build(webpack): add webpack & gulp support
  .gitignore
  docs/.keep
  gulpfile.js
  img/logo-light.png
  img/logo.png
  img/youzhang.png
  package-lock.json
  package.json
  readme.md
  src/assets/.keep
  src/assets/data/.keep
  src/assets/data/members-manifest.json
  src/assets/data/projects.json
  src/css/opensource_uc.css
  src/css/stisla.css
  src/favicon.png
  src/img/hero.jpg
  src/img/icons/icon-512x512.png
  src/img/map.png
  src/img/news/img01.jpg
  src/img/news/img02.jpg
  src/img/news/img03.jpg
  src/img/news/img04.jpg
  src/img/news/img05.jpg
  src/img/news/img06.jpg
  src/img/pizarra.JPG
  src/img/projects.jpeg
  src/img/spinner.svg
  src/index.html
  src/js/app.js
  src/js/jquery.easeScroll.js
  src/js/load-team.js
  src/js/opensource_uc.js
  src/js/stisla.js
  src/manifest.json
  src/service-worker.js
  webpack.config.js
Labels: enhancement

#43 change bg color "ver todos los miembros"
  src/css/opensource_uc.css
Labels: bug

#45 Agregado nombre Maximiliano Militzer
  src/assets/data/members-manifest.json
Labels: good first issue

#48 Add webpack to production
  .gitignore
  contributing.md
  docs/.keep
  gulpfile.js
  img/logo-light.png
  img/logo.png
  img/youzhang.png
  package-lock.json
  package.json
  readme.md
  src/assets/.keep
  src/assets/data/.keep
  src/assets/data/members-manifest.json
  src/assets/data/projects.json
  src/css/opensource_uc.css
  src/css/stisla.css
  src/favicon.png
  src/img/hero.jpg
  src/img/icons/icon-512x512.png
  src/img/map.png
  src/img/news/img01.jpg
  src/img/news/img02.jpg
  src/img/news/img03.jpg
  src/img/news/img04.jpg
  src/img/news/img05.jpg
  src/img/news/img06.jpg
  src/img/pizarra.JPG
  src/img/projects.jpeg
  src/img/spinner.svg
  src/index.html
  src/js/app.js
  src/js/jquery.easeScroll.js
  src/js/load-team.js
  src/js/opensource_uc.js
  src/js/stisla.js
  src/manifest.json
  src/service-worker.js
  webpack.config.js
Labels: enhancement
